### ISSUE TITLE
文章的右边目录没有显示全

### ISSUE THREAD

**Issue by JssDream** [Programming-With-Love/solo-nexmoe#1]
![image-47b0d511](https://user-images.githubusercontent.com/24471999/63635363-862bfd00-c694-11e9-9ed0-8686cef370f3.png)

> 笔记本:15.6寸的，chrome！瞅瞅什么情况？  @JinJianh

**Comment by gooolan** [comment]
电脑分辨率多少呢，看样子是因为分辨率的原因，或者截取全屏我看下


 
---原始邮件---
发件人: "JssDream"<notifications@github.com>
发送时间: 2019年8月24日 17:29:22
收件人: "JinJianh/solo-nexmoe"<solo-nexmoe@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"金戋"<1576962841@qq.com>;
主题: [JinJianh/solo-nexmoe] 文章的右边目录没有显示全 (#1)




  
笔记本:15.6寸的，chrome！瞅瞅什么情况？  @JinJianh

**Comment by JssDream** [comment]
![image](https://user-images.githubusercontent.com/24471999/63635459-752fbb80-c695-11e9-8294-4a414d782466.png)
分辨率：1366*768

**Comment by JssDream** [comment]
电脑比较老了，最高分辨率了已经

**Comment by gooolan** [comment]
分辨率太小的原因，我后面做下修改，分辨率太小就隐藏掉目录就可以了   感谢提出的问题


 
---原始邮件---
发件人: "JssDream"<notifications@github.com>
发送时间: 2019年8月24日 17:35:29
收件人: "JinJianh/solo-nexmoe"<solo-nexmoe@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"金戋"<1576962841@qq.com>;
主题: Re: [JinJianh/solo-nexmoe] 文章的右边目录没有显示全 (#1)




 分辨率：1366*768

**Comment by JssDream** [comment]
小事儿

**Comment by gooolan** [comment]
已修复
