### ISSUE TITLE
建议增加去掉预览图选项

### ISSUE THREAD

**Issue by adlered** [Programming-With-Love/solo-nexmoe#12]
closed

**Comment by gooolan** [comment]
不加，over


 
---原始邮件---
发件人: "Adlered"<notifications@github.com&gt;
发送时间: 2019年10月3日 17:03:03
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [InkDP/solo-nexmoe] 建议增加去掉预览图选项 (#12)



closed

**Comment by adlered** [comment]
closed

**Comment by adlered** [comment]
忘了close了
