### ISSUE TITLE
希望可以去掉这个便签前面的#号，换成🏷或者图标的形式

### ISSUE THREAD

**Issue by zouchanglin** [Programming-With-Love/solo-nexmoe#13]
![image](https://user-images.githubusercontent.com/29838710/66711076-383f9580-edb7-11e9-8135-b3401d5957f7.png)

**Comment by zouchanglin** [comment]
这个主题真心好看，希望在这一点上可以改进，谢谢啦

**Comment by gooolan** [comment]
这是风格，如果你不喜欢可以自己改一下，在side.ftl里面

**Comment by zouchanglin** [comment]
可是我不知道在哪改呀，请问应该怎么改呢？
------------------------------------------------------------------
发件人：墨殇 <notifications@github.com>
发送时间：2019年10月13日(星期日) 13:00
收件人：Programming-With-Love/solo-nexmoe <solo-nexmoe@noreply.github.com>
抄　送：zouchanglin <zchanglin@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成🏷或者图标的形式 (#13)

这是风格，如果你不喜欢可以自己改一下，在side.ftl里面

**Comment by gooolan** [comment]
base.css里面有content:"#"&nbsp; 删了即可


 
---原始邮件---
发件人: "zouchanglin"<notifications@github.com&gt;
发送时间: 2019年10月13日 13:13:25
收件人: "Programming-With-Love/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;;
主题: Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成或者图标的形式 (#13)


可是我不知道在哪改呀，请问应该怎么改呢？
 ------------------------------------------------------------------
 发件人：墨殇 <notifications@github.com&gt;
 发送时间：2019年10月13日(星期日) 13:00
 收件人：Programming-With-Love/solo-nexmoe <solo-nexmoe@noreply.github.com&gt;
 抄　送：zouchanglin <zchanglin@aliyun.com&gt;; Author <author@noreply.github.com&gt;
 主　题：Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成🏷或者图标的形式 (#13)
 
 这是风格，如果你不喜欢可以自己改一下，在side.ftl里面

**Comment by zouchanglin** [comment]
好了，改了，谢谢哈
------------------------------------------------------------------
发件人：墨殇 <notifications@github.com>
发送时间：2019年10月13日(星期日) 13:19
收件人：Programming-With-Love/solo-nexmoe <solo-nexmoe@noreply.github.com>
抄　送：zouchanglin <zchanglin@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成🏷或者图标的形式 (#13)

base.css里面有content:"#"&nbsp; 删了即可 



 ---原始邮件--- 
 发件人: "zouchanglin"<notifications@github.com&gt; 
 发送时间: 2019年10月13日 13:13:25 
 收件人: "Programming-With-Love/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;; 
 抄送: "State change"<state_change@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;; 
 主题: Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成或者图标的形式 (#13) 


 可是我不知道在哪改呀，请问应该怎么改呢？ 
 ------------------------------------------------------------------ 
 发件人：墨殇 <notifications@github.com&gt; 
 发送时间：2019年10月13日(星期日) 13:00 
 收件人：Programming-With-Love/solo-nexmoe <solo-nexmoe@noreply.github.com&gt; 
 抄　送：zouchanglin <zchanglin@aliyun.com&gt;; Author <author@noreply.github.com&gt; 
 主　题：Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成🏷或者图标的形式 (#13) 

 这是风格，如果你不喜欢可以自己改一下，在side.ftl里面

**Comment by zouchanglin** [comment]
请这个社交按钮在那里加？

**Comment by gooolan** [comment]
社区设置，然后每天的某个时间段会同步


 
---原始邮件---
发件人: "zouchanglin"<notifications@github.com&gt;
发送时间: 2019年10月13日 14:15:53
收件人: "Programming-With-Love/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;;
主题: Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成或者图标的形式 (#13)


请这个社交按钮在那里加？

**Comment by zouchanglin** [comment]
好滴


------------------------------------------------------------------
发件人：墨殇 <notifications@github.com>
发送时间：2019年10月13日(星期日) 14:16
收件人：Programming-With-Love/solo-nexmoe <solo-nexmoe@noreply.github.com>
抄　送：zouchanglin <zchanglin@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成🏷或者图标的形式 (#13)

社区设置，然后每天的某个时间段会同步 



 ---原始邮件--- 
 发件人: "zouchanglin"<notifications@github.com&gt; 
 发送时间: 2019年10月13日 14:15:53 
 收件人: "Programming-With-Love/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;; 
 抄送: "State change"<state_change@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;; 
 主题: Re: [Programming-With-Love/solo-nexmoe] 希望可以去掉这个便签前面的#号，换成或者图标的形式 (#13) 


 请这个社交按钮在那里加？
