### ISSUE TITLE
文章内，浏览器比例80%以下才能显示导航条

### ISSUE THREAD

**Issue by dik111** [Programming-With-Love/solo-nexmoe#19]
显示器分辨率1920*1080

需要把浏览器(chrome,firefox)的浏览比例调整到80%以下，才能显示文章内的导航条

![QQ图片20191201092312](https://user-images.githubusercontent.com/34541162/69908052-8d457280-141c-11ea-8d73-768ccae0d2d7.png)

**Comment by gooolan** [comment]
显示侧边导航条的条件是大于1725PX且不再最顶部
