### ISSUE TITLE
个性化配置问题

### ISSUE THREAD

**Issue by ReyRen** [Programming-With-Love/solo-nexmoe#3]
@InkDP 十分感谢精彩的主题
有几个问题想向您请教:
1. 主页头头像总是刷不出来. 偶尔回退时能刷出来, 请问这是单单和网络延迟有关吗？
2. 在你的主页下面的导航管理栏中如何控制不需要的一些按钮，比如RSS， 管理等。因为在数据库中我也没发现有这几项
3. 在你的导航管理栏有"关于我"和"我在github上的项目", 这两个子页的链接是怎么设置的, 我在发布这两片文章的时候指定链接必需是指定格式(应该是针对于文章的链接格式进行过滤了). 比如你的"关于我" 的链接是htt[s://XXX/about. 我看这样的好处是简洁并且不会出现在文章栏中.
4. 在你的“标签”(导航管理栏), 是怎么创建的. 

十分感谢得到您的恢复.

**Comment by gooolan** [comment]
听你的描述，我感觉你的版本可能存在问题&nbsp; 能方便提供一下博客地址或者截图吗
 
---原始邮件---
发件人: "whoami"<notifications@github.com&gt;
发送时间: 2019年8月28日 19:36:34
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;;
主题: [InkDP/solo-nexmoe] 配置问题 (#3)



@InkDP 十分感谢精彩的主题
 有几个问题想向您请教:
  
主页头头像总是刷不出来. 偶尔回退时能刷出来, 请问这是单单和网络延迟有关吗？ 

在你的主页下面的导航管理栏中如何控制不需要的一些按钮，比如RSS， 管理等。因为在数据库中我也没发现有这几项 

在你的导航管理栏有"关于我"和"我在github上的项目", 这两个子页的链接是怎么设置的, 我在发布这两片文章的时候指定链接必需是指定格式(应该是针对于文章的链接格式进行过滤了). 比如你的"关于我" 的链接是htt[s://XXX/about. 我看这样的好处是简洁并且不会出现在文章栏中. 

在你的“标签”(导航管理栏), 是怎么创建的. 
 
十分感谢得到您的恢复.

**Comment by ReyRen** [comment]
> 听你的描述，我感觉你的版本可能存在问题&nbsp; 能方便提供一下博客地址或者截图吗

www.reyren.cn 详细问题我十点回家后给你提供. 十分感谢

**Comment by gooolan** [comment]
1，应该是你的网络问题
2，rss与管理属于solo不可或缺的一部分，但是放到导航栏确实有问题，切换到temporary分支即可
3，请在solo后台的导航管理中设置
4，同2切换分支即可
 
---原始邮件---
发件人: "whoami"<notifications@github.com&gt;
发送时间: 2019年8月28日 19:36:34
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;;
主题: [InkDP/solo-nexmoe] 配置问题 (#3)



@InkDP 十分感谢精彩的主题
 有几个问题想向您请教:
  
主页头头像总是刷不出来. 偶尔回退时能刷出来, 请问这是单单和网络延迟有关吗？ 

在你的主页下面的导航管理栏中如何控制不需要的一些按钮，比如RSS， 管理等。因为在数据库中我也没发现有这几项 

在你的导航管理栏有"关于我"和"我在github上的项目", 这两个子页的链接是怎么设置的, 我在发布这两片文章的时候指定链接必需是指定格式(应该是针对于文章的链接格式进行过滤了). 比如你的"关于我" 的链接是htt[s://XXX/about. 我看这样的好处是简洁并且不会出现在文章栏中. 

在你的“标签”(导航管理栏), 是怎么创建的. 
 
十分感谢得到您的恢复.

**Comment by ReyRen** [comment]
@InkDP 感谢, 问题全部解决. Q1确实是网络问题. 可以close了.

**Comment by gooolan** [comment]
后期得到需要的solo参数就会去掉这个分支，就全部在master上了




------------------ 原始邮件 ------------------
发件人: "whoami"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 晚上10:56
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com>;
抄送: "胡钱玲"<1576962841@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [InkDP/solo-nexmoe] 个性化配置问题 (#3)




@InkDP 感谢, 问题全部解决. Q1确实是网络问题. 可以close了.
