### ISSUE TITLE
评论显示成浏览数目

### ISSUE THREAD

**Issue by zeekling** [Programming-With-Love/solo-nexmoe#4]
文章存在评论的时候,会把评论数量当成浏览量:详细如下图所示:
![pic](https://www.zeekling.cn/gogsPics/other/Screenshot%20at%202019-08-30%2021-14-14.png)

**Comment by gooolan** [comment]
已解决，请拉去最新版本更新

**Comment by gooolan** [comment]
已将您的博客添加至solo示例中

**Comment by zeekling** [comment]
已经切换到solo-nexmeo皮肤
