### ISSUE TITLE
文章第一次评论时，无法直接更新只评论列表

### ISSUE THREAD

**Issue by zeekling** [Programming-With-Love/solo-nexmoe#8]
文章第一次评论时,不会刷新评论结果,需要重新刷新界面才能看到评论.

**Comment by gooolan** [comment]
更新值最新版本即可

**Comment by zeekling** [comment]
晚上跟新的master分支的版本.

**Comment by gooolan** [comment]
不应该啊，这个问题早就修复了，你可以看我博客，就是实时的。




------------------ 原始邮件 ------------------
发件人: "zeekling"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 晚上10:32
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com>; 
抄送: "胡钱玲"<1576962841@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [InkDP/solo-nexmoe] 文章第一次评论时,不会刷新评论结果 (#8)




晚上跟新的master分支的版本.

**Comment by zeekling** [comment]
结果如下:
![pic](https://www.zeekling.cn/gogsPics/other/Screenshot%20at%202019-09-09%2022-35-23.png)

**Comment by zeekling** [comment]
我重新升级下,再试下.

**Comment by gooolan** [comment]
可是明天在测试，一会儿我会将你说的置顶加上  估计就半个小时内




------------------ 原始邮件 ------------------
发件人: "zeekling"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 晚上10:38
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com>; 
抄送: "胡钱玲"<1576962841@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [InkDP/solo-nexmoe] 文章第一次评论时,不会刷新评论结果 (#8)




我重新升级下,再试下.

**Comment by zeekling** [comment]
好的

**Comment by zeekling** [comment]
刚试了下你的,也不行
![pic](https://www.zeekling.cn/gogsPics/other/Screenshot%20at%202019-09-09%2022-46-47.png)

**Comment by gooolan** [comment]
> 刚试了下你的,也不行
> ![pic](https://camo.githubusercontent.com/36c54a819301d5c35e1be1312ad7e23792e34933/68747470733a2f2f7777772e7a65656b6c696e672e636e2f676f6773506963732f6f746865722f53637265656e73686f742532306174253230323031392d30392d303925323032322d34362d34372e706e67)

我自己测试是可以的，难道是浏览器的原因？

**Comment by zeekling** [comment]
浏览器版本信息:


Google Chrome | 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux
JavaScript | V8 7.5.288.30
Flash | 32.0.0.238 /home/zeek/.config/google-chrome/PepperFlash/32.0.0.238/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end

**Comment by zeekling** [comment]
用火狐试了下也还是不行.

**Comment by gooolan** [comment]
> 用火狐试了下也还是不行.

已修复

**Comment by zeekling** [comment]
刚试了下,好了.
