### ISSUE TITLE
Markdown语法不高亮

### ISSUE THREAD

**Issue by ReyRen** [Programming-With-Love/solo-nexmoe#9]
我看你的网站上也正常显示, 我的代码语法不高亮
<img width="688" alt="image" src="https://user-images.githubusercontent.com/26827250/64579183-875b6a80-d3b4-11e9-8b5a-46297dc55d56.png">
发生在昨天从b3log docker hub拉取了最新的image, nexmoe之前一直是temporary分支, 现在切到了master也依然问题存在. 
求问有碰到过类似的或者可能是什么问题吗?

**Comment by gooolan** [comment]
> 我看你的网站上也正常显示, 我的代码语法不高亮
> <img alt="image" width="688" src="https://user-images.githubusercontent.com/26827250/64579183-875b6a80-d3b4-11e9-8b5a-46297dc55d56.png">
> 发生在昨天从b3log docker hub拉取了最新的image, nexmoe之前一直是temporary分支, 现在切到了master也依然问题存在.
> 求问有碰到过类似的或者可能是什么问题吗?

不知道你的博客为何会出现这种问题，查看[语法高亮测试](https://www.jinjianh.com/articles/2019/09/10/1568082711923.html)，里面代码都是从你博客里面copy来的

**Comment by ReyRen** [comment]
hmmm, solo image的问题? 关键是在编辑的时候预览模式下一切正常. 不行我区solo问一下. 
谢谢了~ (觉得可以的话就关了吧)

**Comment by gooolan** [comment]
> hmmm, solo image的问题? 关键是在编辑的时候预览模式下一切正常. 不行我区solo问一下.
> 谢谢了~ (觉得可以的话就关了吧)

刚刚看了代码块儿的源码，跟我的差异很大，这个问题应该不是我皮肤的问题，方便的话可以在社区私发我一下[二进制中1的个数](https://www.reyren.cn/articles/2019/09/06/1567756312895.html)的源码吗

**Comment by ReyRen** [comment]
@InkDP 已发送, 十分感谢帮忙

**Comment by ReyRen** [comment]
@InkDP 会不会是[Markdown HTTP 渲染引擎切换为 Lute](https://github.com/b3log/solo/issues/12871)这个问题

**Comment by gooolan** [comment]
> @InkDP 已发送, 十分感谢帮忙
好像是solo更新了啥东西，从而大导致了代码块的解析出现了问题，我估计是lute

**Comment by gooolan** [comment]
> @InkDP 已发送, 十分感谢帮忙
好像是solo更新了啥东西，从而大导致了代码块的解析出现了问题，我估计是lute

**Comment by gooolan** [comment]
> @InkDP 会不会是[Markdown HTTP 渲染引擎切换为 Lute](https://github.com/b3log/solo/issues/12871)这个问题

就是这个问题，我去问下怎么改

**Comment by gooolan** [comment]
已解决，拉取最新的查看

**Comment by ReyRen** [comment]
@InkDP 完美~~ 感谢万分

**Comment by gooolan** [comment]
我看了一下，为啥你的成黑色的了😂😂


 
---原始邮件---
发件人: "whoami"<notifications@github.com&gt;
发送时间: 2019年9月10日 16:56:28
收件人: "InkDP/solo-nexmoe"<solo-nexmoe@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;;
主题: Re: [InkDP/solo-nexmoe] Markdown语法不高亮 (#9)



@InkDP 完美~~ 感谢万分
